### PR TITLE
feat(office): list and expand plugin slash commands in the pane

### LINKED ISSUE #2480: Office pane: plugin slash commands are neither listed nor executable
## Problem

The engine discovers every `commands/*.md` an installed plugin ships — verified from
`~/MEDDPICC/CUSTOMER-C` with `meddpicc@f5-sales-demo-marketplace`, `discoverSlashCommands`
returns all six, prefixed `meddpicc:`. The Office pane can use none of them.

### Nothing advertises them

`browser/chat-protocol.ts` has `list_skills`/`skills` and no command equivalent, and
`ChatPanel.tsx` passes `skills` to `Composer` but never `slashCommands` — so the
`SlashCommandMenu` the shared chat-ui already ships (`chat-ui/src/index.ts`) never
renders. The `/` button simply does not appear.

### Typing one does nothing

`chat-handler.ts` calls `session.prompt(...)` with `expandPromptTemplates: false`, which
skips the expansion branch in `AgentSession.prompt` entirely. Even with that flag on it
would still fail, because `composeChatPrompt` appends the user's text **last** — by the
time `prompt` sees the string it no longer starts with `/`.

So `/meddpicc:qualify-deal CUSTOMER-C` reaches the model as literal prose. The model answers
*about* the string instead of following the command.

### VS Code has the same hole

`modes/rpc/rpc-mode.ts` has a `list_skills` command and no `list_commands`, so the VS Code
webview cannot enumerate them either.

## Scope

- `list_commands` / `commands` frames on the bridge, mirroring `list_skills` / `skills`,
  with a shared `toSlashCommandSummaries` projection beside `toSkillSummaries` so the two
  transports cannot drift into shipping different amounts. The template bodies must not
  cross the wire — they are prompt templates that can run to hundreds of lines.
- Expand in `chat-handler`, on `req.text`, **before** `composeChatPrompt`. Reuse the
  existing `expandSlashCommand`; do not write a second expander.
- An unmatched `/name` must pass through unchanged — skills use the same spelling and are
  handled by the system prompt, so rewriting or rejecting one would break them.
- `AgentSession.slashCommands` getter, mirroring `get skills()`.
- Pane: request on connect, pass `slashCommands`/`onSlashSelect` to `Composer`.
- Same command on the RPC surface so VS Code does not fall a third release behind.
- Bump `contractVersion`; the contract's `messages` list and `chat-conformance.json` do
  not currently record the enumeration frames at all.

## Acceptance criteria

- [ ] A `/` menu lists the installed plugin's six commands with their descriptions.
- [ ] `/meddpicc:meddpicc-status` reaches the model as the command body, not the literal
      string; `$ARGUMENTS` is substituted; the host system-directive still wraps it.
- [ ] An unknown `/name`, a mid-text slash, and ordinary prose are all untouched.
- [ ] Conformance schemas + golden valid/invalid examples exist for the new frames.
- [ ] Full suite, `check:types`, and lint green; mutation-checked.

### PR DESCRIPTION
**Pull request by robinmordasiewicz**
Closes #2480

## What was broken

The engine already discovers every `commands/*.md` an installed plugin ships. The pane
could use none of them.

**Nothing advertised them.** `chat-protocol.ts` had `list_skills`/`skills` and no command
equivalent, so `ChatPanel` never passed `slashCommands` to `Composer` and the
`SlashCommandMenu` the shared chat-ui *already ships* never rendered — the `/` button
simply did not appear.

**Typing one did nothing.** `chat-handler` calls `session.prompt(...)` with
`expandPromptTemplates: false`, which skips the expansion branch. Even with that flag on
it would still fail: `composeChatPrompt` appends the user's text **last**, so by the time
`prompt` sees the string it no longer starts with `/`. `/meddpicc:qualify-deal CUSTOMER-C`
reached the model as literal prose, and the model answered *about* the string.

## Verified against the real plugin

From `~/MEDDPICC/CUSTOMER-C`, driving the same discovery path a session uses:

```
MENU (what list_commands sends):
  /meddpicc:build-map        — Build a buyer-approved Mutual Action Plan tied to MEDDPICC
  /meddpicc:champion-test    — Test whether your contact is a true MEDDPICC champion
  /meddpicc:deal-review      — Facilitate a structured weekly MEDDPICC deal review
  /meddpicc:meddpicc-status  — Check MEDDPICC framework readiness and deal data availability
  /meddpicc:qualify-deal     — Score and qualify a deal using the MEDDPICC framework…
  /meddpicc:update-deal      — Ingest meeting notes, emails, transcripts, OSINT reports…

EXPANSION of /meddpicc:meddpicc-status →
  Report MEDDPICC framework readiness and per-deal status. The
  deterministic status (ordering, completion, scores) comes from the
  plugin engine — never count files or compute scores by hand.

unknown /name passthrough: "/not-a-command x"
```

## Design notes

**Expansion lives in the handler, on `req.text`, before composition** — the only point
where the text still starts with `/`. It reuses the existing `expandSlashCommand` rather
than growing a second expander.

**An unmatched `/name` passes through untouched.** Skills are invoked by the same spelling
but handled by the system prompt, so rewriting or rejecting an unknown name would break
them. There is a test for exactly this.

**`toSlashCommandSummaries` sits beside `toSkillSummaries`** for the reason that one
exists: bridge and RPC project through a single function, so they cannot drift into
shipping different amounts. Command bodies never cross the wire — they are prompt
templates that can run to hundreds of lines, and a menu needs a label.

**VS Code gets the matching `list_commands` RPC command**, so its webview does not fall
another release behind the pane.

## Contract

Bumped to **1.12.0**. While adding the new frames I found the contract never recorded the
enumeration frames at all — `list_skills`/`skills` were missing from both the `messages`
list and `chat-conformance.json`. All four are now registered, with schemas and golden
valid/invalid examples (empty list, name-keyed map instead of array, entry without a
description, entry with an empty name).

## Test-fake hygiene

Nine chat-handler fakes omitted `slashCommands` and passed only because nothing read it —
the `as unknown as AgentSession` cast hides the gap from tsc. Adding one read surfaced 31
failures at once. They now declare the field.

## Verification

- 9 new tests. **Mutation-checked**: reverting the expansion to `req.text` fails three of
  them (confirmed) — enumeration, argument substitution, and the host-prompt wrapper.
- `packages/coding-agent`: 5868 pass / 0 fail. `packages/office-pane`: 365 pass / 0 fail
  (conformance drift guard included).
- `bun run check:types` clean; biome clean on all 21 changed files.
- Codex `verified-code-review` (`adversarial-review --base origin/main`): **0 findings**.

## Unrelated breakage found, not fixed here

`bun run check:tools` is **red on `main`**: `internal-urls/xcsh-protocol.ts:654,657` fail
biome's `useTemplate`, introduced by #2447. CI runs `check:rs` but never `check:tools`, so
nothing caught it. Confirmed pre-existing by stashing this branch and re-running. Out of
scope here — filing separately rather than smuggling a drive-by fix into this diff.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by robinmordasiewicz** [comment]
## Correction to this PR's description

The closing section claimed:

> `bun run check:tools` is **red on `main`** … CI runs `check:rs` but never `check:tools`, so nothing caught it.

**Both halves are wrong, and I'm striking them.**

1. CI *does* run it. `ci:check:full` → `check:ts` → `check:tools`. My grep looked for the
   literal string in the workflow and missed two levels of npm-script indirection.
2. `main` is not red. The `xcsh-protocol.ts` `useTemplate` diagnostics are **info-level** —
   `biome check .` reports "Found 2 infos" and exits **0**. I saw the diagnostic block,
   grepped for `error`, matched the word inside biome's own output, and concluded the wrong
   thing. Main's `check` job is green on every recent commit, including current HEAD.

There is nothing to file, and no drive-by fix was warranted.

## What actually failed

My own change. The `check` job caught two real type errors:

```
src/panel/useChatSession.ts(258,23): error TS2322: Type '"list_commands"' is not
  assignable to type '"chat_request" | "chat_stop" | … | "list_skills" | …'
src/panel/useChatSession.ts(291,26): error TS2339: Property 'commands' does not exist on type 'never'
```

I added the frames to `chat-protocol.ts` and the office-pane's re-exports but not to
`ChatOutbound` / `ChatInboundMsg`, the unions the transport is actually typed against.

It slipped past me locally because `bun run check:types` **at the repo root** only compiles
`tsconfig.tools.json` — the office-pane's own `check:types` is a separate project — and
`bun test` does not typecheck, so the package's 365 tests passed while its types did not.
Running the full `bun run check:ts` reproduces it, and that is what I should have run
before pushing. Fixed in c6ec1f4e8; `bun run check:ts` is now clean end to end.
