### ISSUE TITLE
revert: remove #308 utils changes accidentally included in #319

### ISSUE THREAD

**Issue by robinmordasiewicz** [f5-sales-demo/xcsh#321]
## Problem

The squash merge of PR #319 (commit 845f1302b) included `packages/utils/` changes from issue #308 that leaked in via dirty worktree state. Only the `packages/coding-agent/src/services/` renames from #307 were intended.

This caused issue #308 to be incorrectly closed.

## Solution

Revert the two utils files to their pre-merge state:
- `packages/utils/src/dirs.ts`
- `packages/utils/test/f5xc-dirs.test.ts`

This allows #308 to be re-done cleanly in its own dedicated PR.

**Comment by robinmordasiewicz** [comment]
## CI Status for PR #320

**PR:** #320
**Run:** 24909561091

### Passing Checks
- `check / Check linked issues` -- PASS (after PR body update with `Closes #321`)
- `native (ubuntu-22.04, linux, x64, modern)` -- PASS
- `native (ubuntu-22.04, linux, x64, baseline, true)` -- PASS

### Failing Checks (pre-existing on main)
- `check` -- FAIL (broken import paths from PR #319)
- `test` -- FAIL (Cannot find module `f5xc-profile*` -- files renamed to `f5xc-context*` by PR #319)
- `install_methods` -- FAIL (build fails due to same import path issue)

### Root Cause
These failures exist on `main` at commit 845f1302b (before this revert). PR #319 renamed service files from `f5xc-profile*` to `f5xc-context*` but did not update the import paths in consumer files:
- `packages/coding-agent/src/slash-commands/builtin-registry.ts`
- `packages/coding-agent/src/modes/components/welcome.ts`
- `packages/coding-agent/src/modes/components/welcome-checks.ts`
- `packages/coding-agent/src/modes/components/status-line/segments.ts`

This revert (reverting utils files only) does NOT introduce any new failures.

### Action Required
The required status checks will block merge. These pre-existing failures need to be fixed in a separate PR to unblock this revert.

**Comment by robinmordasiewicz** [comment]
Not needed — no revert required.
